name: "Cloudfix-Linter-Test"

on:
  pull_request:

jobs:  
  assign:
    name: "Cloudfix-Linter-Test"
    runs-on: ubuntu-latest
    steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.0
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Checkout
      uses: actions/checkout@v3

    - name: Initialise terraform
      run: terraform init

    - name: "Recom"
      if: github.event_name == 'pull_request'
      uses: trilogy-group/cloudfix-linter-github-action@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        pr_number: ${{ github.event.pull_request.number }}
        repository: ${{ github.repository }}
        mock_recommendations: 'true'
        cloudfix_username: ${{ secrets.CLOUDFIX_USERNAME }}
        cloudfix_password: ${{ secrets.CLOUDFIX_PASSWORD }}
        terraform_binary_path: ${{ env.TERRAFORM_CLI_PATH }}/terraform-bin
