name: "Cloudfix-Linter-Test"

on:
  pull_request:

jobs:
  assign:
    name: "Cloudfix-Linter-Test"
    runs-on: ubuntu-latest
    steps:
      - name: "Recco"
      - uses: trilogy-group/cloudfix-linter-github-action@main
